version: "2"

services:
  postgres:
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=entretien
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
